name: osc_prod
services:
  osc:
    build:
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - '6374:6374/udp'
    restart: unless-stopped
    volumes:
      - osc_telemetry:/osc-telemetry
volumes:
  osc_telemetry:
    driver: local
    driver_opts:
      type: 'nfs'
      o: 'addr=truenas.lan,nfsvers=4,soft,nolock'
      device: ":/mnt/data-pool/shared/osc-telemetry"
