name: osc-telemetry_dev
services:
  osc:
    build:
      context: ..
      target: dev
    ports:
      - '7374:6374/udp'
    volumes:
      - ..:/app
      - app_node_modules:/app/node_modules
      - ./test-dir:/osc-telemetry
volumes:
  app_node_modules:
